# Generated by Django 3.2.25 on 2026-10-04 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('previous_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=128)),
                ('current_hash', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointScan',
            fields=[
                ('scan_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('convoy_id', models.CharField(max_length=50)),
                ('checkpoint_name', models.CharField(max_length=150)),
                ('scan_type', models.CharField(max_length=50)),
                ('scanned_by_role', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(max_length=128)),
                ('hmac_signature', models.CharField(max_length=128)),
                ('validated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convoy',
            fields=[
                ('convoy_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('origin', models.CharField(default='Leh Central Supply Depot', max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('driver_name', models.CharField(default='Subedar R. Singh', max_length=150)),
                ('driver_rank', models.CharField(default='Subedar', max_length=50)),
                ('vehicle_number', models.CharField(default='ALS-7749', max_length=50)),
                ('escort_unit', models.CharField(default='14 Corp Tactical Escort', max_length=150)),
                ('cargo_manifest_json', models.TextField(default='[]')),
                ('status', models.CharField(default='PRE_DEPARTURE', max_length=50)),
                ('eta_hours', models.FloatField(default=6.5)),
                ('checkpoints_json', models.TextField(default='[]')),
                ('completed_checkpoints', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outpost',
            fields=[
                ('post_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('altitude_ft', models.IntegerField(default=14000)),
                ('troops', models.IntegerField(default=45)),
                ('patrol_distance_km', models.FloatField(default=12.5)),
                ('heaters_count', models.IntegerField(default=12)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy (> 7 Days Stock)'), ('WARNING', 'Warning (4-7 Days Stock)'), ('CRITICAL', 'Critical (<= 3 Days Stock)')], default='HEALTHY', max_length=20)),
                ('stockout_days', models.FloatField(default=14.0)),
                ('fuel_current', models.FloatField(default=2400.0)),
                ('fuel_max', models.FloatField(default=5000.0)),
                ('fuel_burn_rate', models.FloatField(default=220.0)),
                ('rations_current', models.FloatField(default=1800.0)),
                ('rations_max', models.FloatField(default=3500.0)),
                ('rations_burn_rate', models.FloatField(default=135.0)),
                ('energy_bars_current', models.FloatField(default=450.0)),
                ('energy_bars_max', models.FloatField(default=1000.0)),
                ('energy_bars_burn_rate', models.FloatField(default=45.0)),
                ('ammo_current', models.FloatField(default=12000.0)),
                ('ammo_max', models.FloatField(default=25000.0)),
                ('ammo_burn_rate', models.FloatField(default=250.0)),
                ('oxygen_current', models.FloatField(default=40.0)),
                ('oxygen_max', models.FloatField(default=100.0)),
                ('oxygen_burn_rate', models.FloatField(default=3.0)),
                ('temp_c', models.FloatField(default=-22.0)),
                ('snowfall_cm', models.FloatField(default=5.0)),
                ('wind_speed_kmh', models.FloatField(default=28.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionIndent',
            fields=[
                ('indent_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('post_name', models.CharField(max_length=150)),
                ('post_id', models.CharField(max_length=50)),
                ('generated_by', models.CharField(default='AI Predictive Engine', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(default='Kerosene / Cold Fuel (56-C)', max_length=200)),
                ('quantity', models.CharField(default='1,500 Liters', max_length=100)),
                ('urgency', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal')], default='CRITICAL', max_length=20)),
                ('predicted_stockout', models.CharField(default='3.5 Days', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by Depot'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('temp_c', models.FloatField(default=-22.0)),
                ('troops_count', models.IntegerField(default=45)),
                ('patrol_distance_km', models.FloatField(default=12.5)),
                ('fuel_burned_liters', models.FloatField()),
                ('rations_burned_pouches', models.FloatField()),
                ('energy_bars_burned', models.FloatField(default=0)),
                ('ammo_burned_rds', models.FloatField(default=0)),
                ('oxygen_burned_units', models.FloatField(default=0)),
                ('logged_by_role', models.CharField(default='POST_COMMANDER', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.outpost')),
            ],
        ),
    ]
